# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160403_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intransit',
            old_name='end_poss',
            new_name='end_pos',
        ),
    ]
